on:
  push:
    branches: [master]

name: "Transifex synchronization"

jobs:
  upload-to-transifex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3   
      
      - name: push sources to transifex
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_TOKEN }}